### ISSUE TITLE
Deactivated Batch processing

### ISSUE THREAD

**Issue by rwutzke** [MarkEdmondson1234/shinyga#11]
Could you please explain why batch processing is disabled (ie commented out):
https://github.com/MarkEdmondson1234/shinyga/blob/master/R/shinyga_fetchdata.R#L868

We would like to use that to pull more than 10000 lines.

Thanks :)

**Comment by MarkEdmondson1234** [comment]
Good question :)

There were some bugs in the rga() when walk and batch flags combined I didn't want to copy over to shinyga(). I figured for most shiny apps 10k rows should be adequate. 

...but, if you would like to have more than 10k, I would now heavily recommend you use my googleAnalyticsR library instead, as it is the spiritual successor of shinyga() and can be used in Shiny apps. It's got lots of other cool features too.

**Comment by rwutzke** [comment]
Thanks, I will try it out. The description looks really promising!
